# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=1000)),
                ('image_link', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=1000)),
                ('content_link', models.CharField(max_length=100)),
            ],
        ),
    ]
