# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 17:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preview',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 25, 17, 9, 5, 845681), verbose_name='date published'),
        ),
    ]
