# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_preview_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preview',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
